### ISSUE TITLE
Version of BMUSE in the scraped data

### ISSUE THREAD

**Issue by petrospaps** [HW-SWeL/BMUSE#67]
The version of BMUSE is already included in a static way, but can change to include a dynamic versioning of BMUSE that will be present at the scraped data level and can solve issues relating to what was the code base that was used to do the scrape. This can help when trying to find the root cause of an issue or inconsistencies between scraped data.

**Comment by AlasdairGray** [comment]
This can be done by adding a triple of the form
``` 
xxx pav:createdWith <github-release-url>
```

**Comment by AlasdairGray** [comment]
The object of the `pav:createdWith` triple needs to be a URL, not a literal value, i.e. the following statement is not valid as it does not tell us the tool that was used.
```
<https://bioschemas.org/crawl/v1/proteinensemble/PED00001/20201126/5999> <http://purl.org/pav/createdWith> "0.0.4-SNAPSHOT"
```

Solutions would be:
```
<https://bioschemas.org/crawl/v1/proteinensemble/PED00001/20201126/5999> <http://purl.org/pav/createdWith> <https://github.com/HW-SWeL/BMUSE#0.0.4-SNAPSHOT>
```
or
```
<https://bioschemas.org/crawl/v1/proteinensemble/PED00001/20201126/5999> <http://purl.org/pav/createdWith> <https://github.com/HW-SWeL/BMUSE/>
<https://github.com/HW-SWeL/BMUSE/> <http://purl.org/pav/version> "0.0.4-SNAPSHOT"
```

Note that in the first option I've used a `#` for the version so that we still have a resolvable URL. However, the URL does not have any meaning.

The advantage of the second approach is that it makes explicit the tool and the version in a machine processable way.
